INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_TESTMODULE testmodule)

FIND_PATH(
    TESTMODULE_INCLUDE_DIRS
    NAMES testmodule/api.h
    HINTS $ENV{TESTMODULE_DIR}/include
        ${PC_TESTMODULE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    TESTMODULE_LIBRARIES
    NAMES gnuradio-testmodule
    HINTS $ENV{TESTMODULE_DIR}/lib
        ${PC_TESTMODULE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TESTMODULE DEFAULT_MSG TESTMODULE_LIBRARIES TESTMODULE_INCLUDE_DIRS)
MARK_AS_ADVANCED(TESTMODULE_LIBRARIES TESTMODULE_INCLUDE_DIRS)

