#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1_AR76780 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 28 11:51:17 PDT 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto b5eb937a5a6f4130a756d5d97370201d --incr --debug all --relax --mt 8 -d "UHD_FPGA_DIR=/home/user/rfdev//uhd/fpga/usrp3/top/../.." -d "WORKING_DIR="/home/user/rfdev/blocks/rfnoc-testmodule/rfnoc/fpga/rfnoc_block_testblock"" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot rfnoc_block_testblock_tb_behav xil_defaultlib.rfnoc_block_testblock_tb xil_defaultlib.glbl -log elaborate.log -timescale 1ns/1ns"
xelab -wto b5eb937a5a6f4130a756d5d97370201d --incr --debug all --relax --mt 8 -d "UHD_FPGA_DIR=/home/user/rfdev//uhd/fpga/usrp3/top/../.." -d "WORKING_DIR="/home/user/rfdev/blocks/rfnoc-testmodule/rfnoc/fpga/rfnoc_block_testblock"" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot rfnoc_block_testblock_tb_behav xil_defaultlib.rfnoc_block_testblock_tb xil_defaultlib.glbl -log elaborate.log -timescale 1ns/1ns

